image: php:8.1

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: your_database_name
  MYSQL_USER: your_user
  MYSQL_PASSWORD: your_password
  APP_ENV: testing
  APP_KEY: base64:your_base64_key
  APP_DEBUG: true
  APP_URL: http://localhost

before_script:
  - apt-get update && apt-get install -y unzip git
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --force

test:
  script:
    - php artisan test

deploy:
  stage: deploy
  script:
    - echo "Deploying to your server"
    # Tambahkan perintah deploy Anda di sini
